In [1]:
from sklearn.decomposition import PCA
from sklearn.decomposition import KernelPCA
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import Pipeline
import numpy as np

In [2]:
exec(open("soccerstats.py").read())

In [26]:
df2.head()

0              1    2    3    4    5         6         7   \
0        Hull City  Newcastle Utd  0.0  3.0  0.0  1.0  0.490566  0.761006   
1          Everton  West Bromwich  0.0  0.0  0.0  0.0  0.487500  0.756250   
2  Manchester City        Arsenal  0.0  2.0  0.0  1.0  0.484472  0.751553   
3     West Ham Utd      Hull City  3.0  0.0  0.0  0.0  0.481481  0.746914   
4    Newcastle Utd    Southampton  1.0  2.0  1.0  1.0  0.484663  0.748466   

         8         9   ...      64        65        66        67     68  \
0  0.371069  0.220126  ...  0.0000  0.333333  0.733333  1.866667  0.500   
1  0.368750  0.218750  ...  0.0625  0.312500  1.125000  1.375000  0.875   
2  0.372671  0.217391  ...  0.3125  0.000000  2.000000  0.687500  2.375   
3  0.370370  0.216049  ...  0.0000  0.250000  0.812500  1.312500  1.000   
4  0.374233  0.214724  ...  0.0625  0.000000  1.062500  1.062500  0.625   

      69        70        71        72        73  
0  0.500  0.375000  0.571429  0.250000  0.142857  
1  0.875  0.500000  0.500000  0.250000  0.250000  
2  2.375  0.555556  0.714286  0.333333  0.142857  
3  1.000  0.444444  0.142857  0.222222  0.142857  
4  0.625  0.250000  0.250000  0.250000  0.000000  

[5 rows x 74 columns]

In [3]:
dataframe = df2.iloc[:,[i for i in range(6,74)]]
target = np.where(df2.iloc[:,2] + df2.iloc[:,3] > 2.5,1,0)
dataframe.columns = [i for i in range(68)]
np.unique(target,return_counts=True)

(array([0, 1]), array([530, 575]))

In [65]:
test_forest=RandomForestClassifier(n_estimators=800)
test_forest.fit(dataframe,target)
test_forest.feature_importances_


array([0.02167563, 0.01411547, 0.01348894, 0.01575091, 0.01531586,
       0.01564496, 0.01404942, 0.01586582, 0.0144284 , 0.0147392 ,
       0.01429717, 0.01689902, 0.01808845, 0.01782952, 0.01396864,
       0.0131115 , 0.01473292, 0.01508025, 0.01503762, 0.01478539,
       0.01385686, 0.01430722, 0.01417525, 0.01604075, 0.01372139,
       0.01537414, 0.01590317, 0.01660601, 0.01434964, 0.01587798,
       0.01778162, 0.01519035, 0.01604863, 0.00914619, 0.00920653,
       0.01223599, 0.01224404, 0.01186268, 0.0107545 , 0.01279197,
       0.01639224, 0.01502085, 0.01425279, 0.01325745, 0.01805655,
       0.01688338, 0.01393571, 0.01451929, 0.0125901 , 0.01230534,
       0.01305143, 0.01306449, 0.01832472, 0.01592708, 0.01626163,
       0.01662961, 0.01365868, 0.01981051, 0.01435404, 0.0176882 ,
       0.01445729, 0.02215864, 0.01076953, 0.01000354, 0.01424684,
       0.0128971 , 0.01136627, 0.0117367 ])

In [62]:
test_pca = PCA()
test_pca.fit(dataframe)
nvar = test_pca.explained_variance_ratio_
nvar = list(nvar)
nvar.sort(reverse=True)
for i in range(len(nvar)):
	print(sum(nvar[:i]))

0
0.3690971787669737
0.7070833963524603
0.752814429177123
0.7946316023196522
0.8339242854711795
0.8720389176072064
0.906705916200812
0.9385650924717808
0.9450455164164686
0.9514015334620457
0.9552773731138949
0.9589902580708168
0.9623446142370835
0.965406394357045
0.9683334076318828
0.9708589384712499
0.9732572712880166
0.9755716264360885
0.9776603828888453
0.9796989516082716
0.9816171399951721
0.9831871916701947
0.9847051175732391
0.9861561578127157
0.9876047284141787
0.9888271851856915
0.9900274703331442
0.9910814465506337
0.9920328478180165
0.9929380659888407
0.9938122744923734
0.9946612933756291
0.9954804995039781
0.9961472068302236
0.996759814899578
0.9972853623824824
0.9977661211537417
0.9981726069521255
0.9984744604118319
0.99877022407505
0.9990375934643438
0.9992869213283879
0.9994315210720984
0.999547725423595
0.9996601566003105
0.999757592185766
0.9998465029955298
0.9998963776924435
0.9999304741425729
0.999953793114312
0.9999759793606513
0.999988558410027
0.9999945820398668
0

In [9]:
dataframe_s = dataframe.copy()
for i in range(10,39):
    dataframe_s.iloc[:,i]=dataframe_s.iloc[:,i]-dataframe_s.iloc[:,i+29]/(dataframe_s.iloc[:,i]*dataframe_s.iloc[:,i+29]+1)
for i in range(10,39):
    dataframe_s.drop(labels=i+29,axis=1,inplace=True)
test_forest=RandomForestClassifier(n_estimators=800)
test_forest.fit(dataframe_s,target)
test_forest.feature_importances_

array([0.02654106, 0.02588245, 0.0219986 , 0.02535259, 0.02612231,
       0.02488342, 0.02321552, 0.02365311, 0.02293459, 0.02278337,
       0.030181  , 0.02371625, 0.02316688, 0.02330431, 0.02728295,
       0.02371311, 0.0257311 , 0.02478466, 0.02404756, 0.0257507 ,
       0.02638194, 0.02417206, 0.03039853, 0.02580777, 0.0249635 ,
       0.02968984, 0.02895328, 0.02849398, 0.02541554, 0.02888793,
       0.02719266, 0.02595714, 0.02453058, 0.02525596, 0.02591482,
       0.02763273, 0.02515396, 0.02509085, 0.02506141])

In [84]:
test_pca = PCA()
test_pca.fit(dataframe_s)
nvar = test_pca.explained_variance_ratio_
nvar = list(nvar)
nvar.sort(reverse=True)
for i in range(len(nvar)):
	print(sum(nvar[:i]))

0
0.7140693947629076
0.7957034349515277
0.875343871251752
0.9397518337778938
0.9523520925405042
0.9595728477925627
0.9661220579973128
0.9710087887186093
0.9756502938352051
0.9793961045957875
0.9824525584694954
0.9852627242443652
0.9876431131495454
0.9898009481403547
0.9918442024887313
0.9935321220569139
0.9951767318613964
0.9964821104935272
0.9974710723443804
0.9980591365638836
0.9986013986986522
0.9991235333907196
0.999391406509323
0.9996122450764741
0.9998033442700474
0.9998844187460639
0.9999388112519347
0.9999746626633701
0.999988729292301
0.9999946556863578
0.9999984745385645
0.9999999999999998
0.9999999999999998
0.9999999999999998
0.9999999999999998
0.9999999999999998
0.9999999999999998
0.9999999999999998


In [11]:
X_train,X_test,y_train,y_test=train_test_split(dataframe_s,target,test_size=0.25,stratify=target)

In [95]:
paramgrid={'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [8,10,20,30,40,50,80,100,150,200,300,400]}
grid = GridSearchCV(RandomForestClassifier(),param_grid=paramgrid,cv=10,n_jobs=-2)
grid.fit(X_train,y_train)
print("best score - ",grid.best_score_)
print("best params - ",grid.best_params_)


best score -  0.5591787439613527
best params -  {'bootstrap': True, 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 8}


c:\users\wojcz\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [98]:
pca = PCA(n_components=0.95)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
grid = GridSearchCV(RandomForestClassifier(),param_grid=paramgrid,cv=10,)
grid.fit(X_train_pca,y_train)
print("best score - ",grid.best_score_)
print("best params - ",grid.best_params_)



c:\users\wojcz\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


best score -  0.5748792270531401
best params -  {'bootstrap': False, 'max_depth': 80, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 100}


In [12]:
kpca = KernelPCA(kernel="rbf",n_components=15)
X_train_kpca = kpca.fit_transform(X_train)
nvar2 = kpca.lambdas_
nvar2 = list(nvar2)
nvar2.sort(reverse=True)
for i in range(len(nvar2)):
	print(sum(nvar2[:i]))
test_forest=RandomForestClassifier(n_estimators=800)
test_forest.fit(X_train_kpca,y_train)
test_forest.feature_importances_


0
66.26962063377842
76.45754631257881
85.66328005010232
93.24149350852896
100.37024435965698
102.3797051743813
103.86313956219145
105.0273671791926
106.01838067904777
106.94063575805077
107.80996095093124
108.51180887131305
109.18369341507446
109.74186432058096


array([0.06723445, 0.06337882, 0.06654204, 0.06055826, 0.06790762,
       0.06494705, 0.06692327, 0.0744116 , 0.0675318 , 0.06792723,
       0.06346213, 0.06833673, 0.06543559, 0.06261011, 0.07279329])

In [10]:
clf = Pipeline([("kpca",KernelPCA(n_components=15)),
               ("las",RandomForestClassifier())])
paramgrid_kpca = [{"kpca__gamma": np.linspace(0.03,0.05,10),
                  "kpca__kernel": ["sigmoid","rbf"],
                  'las__bootstrap': [True, False],
                  'las__max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, None],
                  'las__max_features': ['auto', 'sqrt'],
                  'las__min_samples_leaf': [1, 2, 4],
                  'las__min_samples_split': [2, 5, 10],
                  'las__n_estimators': [8,10,20,30,40,50,80,100,150,200,300,400]}]
grid_kpca = GridSearchCV(clf,param_grid=paramgrid_kpca,cv=10,n_jobs=1)
grid_kpca.fit(X_train,y_train)
print("best score - ",grid_kpca.best_score_)
print("best params - ",grid_kpca.best_params_)


0
21.591565657168722
24.02862988358836
26.358755445773557
28.238986517714466
28.57897914365716
28.786951430838435
28.971235353927995
29.12823753422229
29.27349526533961
29.40511954325767
29.503181883617444
29.585393132601446
29.661178713936405
29.728308893400254


array([0.07332567, 0.06382431, 0.06860716, 0.06939667, 0.06264011,
       0.06635395, 0.0633753 , 0.06569726, 0.07668328, 0.06763421,
       0.06704272, 0.06590557, 0.06464628, 0.06203432, 0.06283318])

In [19]:
from sklearn.manifold import LocallyLinearEmbedding
std_scaler = StandardScaler()
X_train_std = std_scaler.fit_transform(X_train)
lle = LocallyLinearEmbedding(n_components=15)
X_train_std_lle = lle.fit_transform(X_train_std,y_train)
test_forest=RandomForestClassifier(n_estimators=800)
test_forest.fit(X_train_std_lle,y_train)
accuracy_score(y_train,cross_val_predict(test_forest,X_train_std_lle,y_train,cv=10))

0.4915458937198068

In [13]:
clf_svc = Pipeline([("kpca",KernelPCA(n_components=15,kernel="rbf")),
                   ("sc",StandardScaler()),
                   ("svm",SVC(max_iter=2000))])
paramgrid_svm = [{
                  "svm__kernel":["rbf"],
                  "svm__C":[0.00001,0.0001,0.001,0.01,0.1,1,10,100,200,300,400],
                  "svm__gamma":[0.00001,0.0001,0.001,0.01,0.1,1,10]},
                 {
                  "svm__kernel":["poly"],
                  "svm__gamma":[0.00001,0.0001,0.001,0.01,0.1,1,10],
                  "svm__C":[0.00001,0.0001,0.001,0.01,0.1,1,10,100],
                  "svm__degree":[2,3]
                 }]

grid_svm = GridSearchCV(clf_svc,param_grid=paramgrid_svm,cv=10,n_jobs=-2)
grid_svm.fit(X_train,y_train)
print("best score - ",grid_svm.best_score_)
print("best params - ",grid_svm.best_params_)                 
                 

best score -  0.5929951690821256
best params -  {'svm__C': 1, 'svm__gamma': 0.1, 'svm__kernel': 'rbf'}


c:\users\wojcz\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
